project:
  type: website
  output-dir: docs

website:
  title: "Yang Xun"
  favicon: static/img/favicon.ico
  site-url: https://yangxun.org
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: https://yangxun96.github.io/cv/CV_YangXun.pdf 
        text: CV
      - href: references.qmd
        text: References

format:
  html:
    theme: 
      - static/html/custom.scss
      

