project:
  type: website
  output-dir: docs

website:
  title: "Yang Xun"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - cv.qmd


format:
  html:
    theme: yeti
    css: styles.css
    toc: true



