project:
  type: website
  output-dir: docs

website:
  title: "Yang Xun"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: https://yangxun96.github.io/cv/CV_YangXun.pdf 
        text: CV

format:
  html:
    theme: 
      - static/html/custom.scss
      

