---
title: "Research"
---

# Job Market Paper

**Corruption and Talent Allocation** - [[PDF](https://yangxun.org/Research/JMP_Xun_2023.pdf)]

<span style="color:#1276f0">
Presentations: NEUDC (2023); EWMES (2023, scheduled)
</span>


<details open>
  <summary>Abstract</summary>
    Talent is a key input in the delivery of public services, yet less is known about what affects the supply of talent for the public sector. This paper studies the role of political corruption in shifting talent allocation across public and private sector careers. I exploit a randomized anti-corruption audit program in Brazil together with comprehensive micro-data on educational and labor market outcomes of college students. Using a generalized difference-in-difference research design, I find that high-ability students in audited municipalities are less likely to choose majors tailored toward public sector careers, such as business administration and law. Moreover, tracking students to the labor market demonstrates that audits also lead to a lower share of high-ability students working as civil servants. Finally, I provide suggestive evidence that the effects of audits on talent allocation can be driven by the perception of lower rent-seeking returns and higher reputation costs. Taken together, these findings highlight an understudied negative consequence of corruption on the economy: the distortion of talent allocation toward rent-seeking in the public sector.
</details>


# Selected Work in Progress
- Economic Dependence and Political Dispute Across the Taiwan Strait (with Chiman Cheung and Tzu-Ting Yang) - [Slides] *Available Soon!*
<details>
  <summary>Abstract</summary>
    Does economic integration foster political affinity, or can it trigger a backlash? We approach this question by investigating an unconventional type of “China shock” in the context of the Taiwanese export surge to mainland China. Applying a shift-share design with newly delineated commuting zones in Taiwan, our preliminary findings suggest that an interquartile change in China export exposure leads to a 1.2\% increase in pro-independence vote shares during 2000-2016. Individual data from socioeconomic surveys reveals similar effects on pro-independence attitudes. We do not, however, find evidence of export exposure affecting inclination toward a more exclusive Taiwanese versus Chinese identity. To understand the mechanisms behind the political backlash of trade integration, we plan to disentangle the potential roles of labor market adjustments to trade versus a direct political deterrence effect from overall economic dependence.
</details>

- Immigration and Assimilation of the Chinese Diaspora in Indonesia
<details>
  <summary>Abstract</summary>
     This paper studies the effects of state-enforced assimilation policy on immigrant integration. I focus on the Chinese diaspora in Indonesia when long-lasting anti-Chinese legislation during the New Order (1966-1998) was revoked after the fall of Suharto. I exploit across-regency differences in ethnic Chinese shares prior to the revoke as a proxy for the intensity of out-group exposure. The difference-in-difference estimates suggest the revoke of the legislation fostered cultural assimilation of Chinese Indonesians, as measured by language use and religious affiliation. Additional data collection is in process to study economic and political assimilation, as ethnic Chinese are perceived as economic insiders but political outsiders in Indonesia. All in all, this study aims to contribute to understanding how state policy affects immigrant integration in the context of south-south migration.
</details>